[project]
name = "todo-api"
version = "0.1.0"
description = "Task management API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.118.0",
    "psycopg-binary>=3.2.10",
    "sqlmodel>=0.0.25",
    "uvicorn[standard]>=0.37.0",
]
